# Generated by Django 5.0 on 2024-10-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255)),
                ('hex_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('weight', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('sim_cart_number', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('cpu_frequency', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('internal_space', models.CharField(choices=[('512 مگابایت', 'Mb 512'), ('1 گیگابایت', 'Gb 1'), ('2 گیگابایت', 'Gb 2'), ('4 گیگابایت', 'Gb 4'), ('6 گیگابایت', 'Gb 6'), ('8 گیگابایت', 'Gb 8'), ('12 گیگابایت', 'Gb 12'), ('16 گیگابایت', 'Gb 16'), ('32 گیگابایت', 'Gb 32'), ('64 گیگابایت', 'Gb 64'), ('128 گیگابایت', 'Gb 128'), ('256 گیگابایت', 'Gb 256'), ('512 گیگابایت', 'Gb 512')], max_length=255)),
                ('ram', models.CharField(choices=[('512 مگابایت', 'Mb 512'), ('1 گیگابایت', 'Gb 1'), ('2 گیگابایت', 'Gb 2'), ('4 گیگابایت', 'Gb 4'), ('6 گیگابایت', 'Gb 6'), ('8 گیگابایت', 'Gb 8'), ('12 گیگابایت', 'Gb 12'), ('16 گیگابایت', 'Gb 16'), ('32 گیگابایت', 'Gb 32'), ('64 گیگابایت', 'Gb 64'), ('128 گیگابایت', 'Gb 128'), ('256 گیگابایت', 'Gb 256'), ('512 گیگابایت', 'Gb 512')], max_length=255)),
                ('refresh_rate', models.CharField(choices=[('30 هرتز', 'Hz 30'), ('60 هرتز', 'Hz 60'), ('120 هرتز', 'Hz 120'), ('240 هرتز', 'Hz 240')], max_length=255)),
                ('screen_technology', models.CharField(choices=[('LED', 'Led'), ('OLED', 'Oled'), ('AMOLED', 'Amoled'), ('SUPER AMOLED', 'Super Amoled'), ('SUPER RETINA', 'Super Retina')], max_length=255)),
                ('radio', models.BooleanField()),
                ('number_of_back_camera', models.CharField(choices=[('1 ماژول دوربین', 'Num 1'), ('2 ماژول دوربین', 'Num 2'), ('3 ماژول دوربین', 'Num 3'), ('4 ماژول دوربین', 'Num 4'), ('5 ماژول دوربین', 'Num 5'), ('6 ماژول دوربین', 'Num 6')], max_length=255)),
                ('os', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android'), ('windows phone', 'Windows Phone')], max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
